services:
  postgres:
    image: 'postgres:16'
    hostname: 'postgres'
    environment:
      POSTGRES_DB: jobplatform
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: jobuser
      PGUSER: jobuser
    ports:
      - '5432:5432'
#  job-platform:
#    volumes:
#      - "./:/job-platform"
#    image: 'job-platform'
#    build:
#      context: .
#    ports:
#      - '8080:8080'
#    depends_on:
#      - postgres
#    command: sh -c "/wait && mvn spring-boot:run"
#    environment:
#      - WAIT_HOSTS=postgres:5432
#      - WAIT_HOSTS_TIMEOUT=30
#      - WAIT_SLEEP_INTERVAL=5
#      - WAIT_HOST_CONNECT_TIMEOUT=30