INSERT INTO skill (name) VALUES
                              ('Java'),
                              ('Python'),
                              ('JavaScript'),
                              ('C++'),
                              ('Ruby'),
                              ('C#'),
                              ('Go'),
                              ('Rust'),
                              ('Swift'),
                              ('Kotlin'),
                              ('PHP'),
                              ('SQL'),
                              ('HTML/CSS'),
                              ('TypeScript'),
                              ('Shell Scripting'),
                              ('R'),
                              ('React.js'),
                              ('Angular'),
                              ('Vue.js'),
                              ('Node.js'),
                              ('Django'),
                              ('Flask'),
                              ('Express.js'),
                              ('Spring Framework'),
                              ('Ruby on Rails'),
                              ('Laravel'),
                              ('Bootstrap'),
                              ('Tailwind CSS'),
                              ('jQuery'),
                              ('HTML5'),
                              ('CSS3'),
                              ('GraphQL'),
                              ('REST APIs'),
                              ('React Native'),
                              ('Flutter'),
                              ('Android Development'),
                              ('iOS Development'),
                              ('Xamarin'),
                              ('AWS'),
                              ('Azure'),
                              ('Google Cloud Platform'),
                              ('Kubernetes'),
                              ('Docker'),
                              ('Terraform'),
                              ('Jenkins'),
                              ('GitLab CI/CD'),
                              ('MySQL'),
                              ('PostgreSQL'),
                              ('MongoDB'),
                              ('Redis'),
                              ('Cassandra'),
                              ('SQLite'),
                              ('Oracle DB'),
                              ('Elasticsearch'),
                              ('MariaDB'),
                              ('DynamoDB'),
                              ('Machine Learning'),
                              ('Deep Learning'),
                              ('Artificial Intelligence'),
                              ('Data Analysis'),
                              ('Data Visualization'),
                              ('Pandas'),
                              ('NumPy'),
                              ('SciPy'),
                              ('TensorFlow'),
                              ('PyTorch'),
                              ('Scikit-learn'),
                              ('Jupyter Notebooks'),
                              ('Tableau'),
                              ('Power BI'),
                              ('Hadoop'),
                              ('Spark'),
                              ('Apache Kafka'),
                              ('Ethical Hacking'),
                              ('Penetration Testing'),
                              ('Cryptography'),
                              ('Network Security'),
                              ('Firewalls'),
                              ('Security Audits'),
                              ('Malware Analysis'),
                              ('Data Encryption'),
                              ('Cloud Security'),
                              ('OWASP'),
                              ('Security Incident Response'),
                              ('Sketch'),
                              ('Figma'),
                              ('Adobe XD'),
                              ('InVision'),
                              ('Photoshop'),
                              ('Illustrator'),
                              ('Wireframing'),
                              ('Prototyping'),
                              ('User Testing'),
                              ('Interaction Design'),
                              ('Visual Design'),
                              ('Agile Methodology'),
                              ('Scrum'),
                              ('Kanban'),
                              ('JIRA'),
                              ('Trello'),
                              ('Asana'),
                              ('MS Project'),
                              ('Product Management'),
                              ('Time Management'),
                              ('Risk Management'),
                              ('Budgeting'),
                              ('Digital Marketing'),
                              ('SEO'),
                              ('SEM'),
                              ('Content Marketing'),
                              ('Social Media Marketing'),
                              ('Market Research'),
                              ('Growth Hacking'),
                              ('Customer Relationship Management (CRM)'),
                              ('Google Analytics'),
                              ('Sales Strategies'),
                              ('Product Strategy'),
                              ('Communication'),
                              ('Leadership'),
                              ('Problem-solving'),
                              ('Creativity'),
                              ('Critical Thinking'),
                              ('Teamwork'),
                              ('Adaptability'),
                              ('Conflict Resolution'),
                              ('Emotional Intelligence'),
                              ('Negotiation'),
                              ('Presentation Skills');